### PR TITLE
WIP: Vararg

### PR DESCRIPTION
**Pull request by DrewCarlson**
@dbaelz Thoughts on something like this for varargs? Still needs proper validation and better tests.

### CODE REVIEW

**Comment by dbaelz** [comment]
Hi, thanks for the PR. I have some ideas how to improve and change the varArgs. Do you want to go further with the PR or should I start changing it?

**Comment by DrewCarlson** [comment]
👍 It's all yours.

**Comment by dbaelz** [comment]
I haven't changed anything since I'm still unsure with some local decision/changes.

In the next two weeks I'm busy with work, a conference and a holiday afterwards. So don't be disappointed if there's little progress. After that, I'm focusing on this PR and the open issues.

**Comment by dbaelz** [comment]
Hi, sorry it took me a while to get back to doing stuff for Konclik. Had a really busy time in November. Finally, I reviewed the PR and fixed some the naming locally. So there are some questions and open points:
- Could you give me access to the PR, so I could change it in here?
- I understand the code, but the use case is a little bit blurry. Can you explain it to me with an example?
- There are some tests missing and we should improve the error handling. I'll tackle them in the next days.

**Pull request closed without merging**
